### PR TITLE
Add template list and instructions on remote setup

### PR DESCRIPTION
**Pull request by KingMob**
This is my first pass. LMK if there's anything you want to change, or feel free to edit it.

I added a couple other templates I found on github. The only major criteria was a description saying what it was for.

I also added a section in the "Writing Templates" doc about preparing a template for remote consumption.

### CODE REVIEW

**Comment by KingMob** [comment]
Closes #40

**Comment by seancorfield** [comment]
Looks good. The only thing I would ask you to change is to use a lib name that allows the git URL to be deduced:
```clojure
net.clojars.myusername/my-template {:git/url "https://github.com/myusername/my-template"
``` 
change this to 
```clojure
io.github.myusername/my-template {
```
I worry that mentioning Clojars might make people think templates can be distributed as jar files (they can't).

**Comment by seancorfield** [comment]
The point of switching to the io.github lib name is to remove git/URL but at this point I'll merge it and remove that afterward.

**Comment by KingMob** [comment]
👍🏻 

Sorry about any confusion.

**Pull request merged**
